export default function SyntheticNotice({
  compact = false,
}: {
  compact?: boolean;
}) {
  return (
    <div
      className={`flex items-start gap-3 rounded-lg border border-amber-300 bg-amber-50 ${
        compact ? "px-3 py-2.5" : "px-4 py-3.5"
      }`}
      role="note"
    >
      <span aria-hidden className="mt-0.5 text-amber-600">
        &#9888;
      </span>
      <p className={`${compact ? "text-xs" : "text-sm"} leading-relaxed text-amber-900`}>
        <strong className="font-semibold">Synthetic data.</strong> These models are
        trained on data generated by <code className="font-mono text-[0.92em]">
        make_synthetic.py</code>, not on real DOL records. Predictions are a
        demonstration of the pipeline and must not be used for legal, immigration,
        or business decisions.
      </p>
    </div>
  );
}
