"""FastAPI service for PERM processing-time and outcome prediction.

    uvicorn api.main:app --reload

Endpoints
    POST /predict/processing-time   days from filing to decision
    POST /predict/outcome           certified / denied / withdrawn / certified-expired
    GET  /explain/{prediction_id}   SHAP attribution for a stored prediction
    GET  /health                    model + store status

Every prediction is stored with its SHAP values so ``/explain`` can return the
attribution for the exact feature row that produced the answer, rather than
recomputing from a re-parsed request and risking a subtly different result.

Every response carries a ``model_quality`` block. These models are fitted to
synthetic data and are weak in specific, measured ways -- the outcome model in
particular predicts `certified` for essentially every input. Returning a bare
number without that context would misrepresent them.
"""

from __future__ import annotations

import os
from contextlib import asynccontextmanager

import numpy as np
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from src.data_prep.reference import SOC_CODE_TITLES, STATE_TO_REGION

from .predictor import (
    BundlePredictor,
    ModelNotLoadedError,
    PredictorRegistry,
    contribution_records,
    derive_features,
    estimated_decision_date,
    input_warnings,
)
from .schemas import (
    CaseInput,
    FieldOption,
    OptionsResponse,
    ExplanationResponse,
    HealthResponse,
    ModelQuality,
    OutcomeProbability,
    OutcomeResponse,
    ProcessingTimeResponse,
    ShapContribution,
)
from .store import PredictionStore, StoredPrediction, utcnow

SYNTHETIC_WARNING = (
    "Models are trained on SYNTHETIC data generated by "
    "src/data_prep/make_synthetic.py. Predictions are not valid for real PERM "
    "cases and must not be used for legal, immigration, or business decisions."
)

# The Next.js dev server runs on a different origin, so the browser will not
# call this API without an explicit CORS allowance. Override for other hosts
# with PERM_API_CORS_ORIGINS as a comma-separated list.
DEFAULT_CORS_ORIGINS = [
    "http://localhost:3000", "http://127.0.0.1:3000",
    "http://localhost:3001", "http://127.0.0.1:3001",
]
CORS_ORIGINS = [
    o.strip() for o in
    os.getenv("PERM_API_CORS_ORIGINS", ",".join(DEFAULT_CORS_ORIGINS)).split(",")
    if o.strip()
]

registry = PredictorRegistry()
store = PredictionStore()


@asynccontextmanager
async def lifespan(app: FastAPI):
    registry.load()
    yield
    store.clear()


app = FastAPI(
    title="PERM Processing Time & Outcome API",
    version="0.1.0",
    description=(
        "Predicts PERM labour-certification processing time and case outcome, with "
        "per-prediction SHAP explanations.\n\n"
        f"**{SYNTHETIC_WARNING}**"
    ),
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=CORS_ORIGINS,
    allow_credentials=False,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["Content-Type"],
)


@app.exception_handler(ModelNotLoadedError)
async def _model_not_loaded(request: Request, exc: ModelNotLoadedError) -> JSONResponse:
    return JSONResponse(status_code=503, content={"detail": str(exc)})


# Python's str.title() mangles the two things these labels are made of:
# "LEVEL III" becomes "Level Iii" and "MASTER'S" becomes "Master'S".
_LABEL_FIXUPS = {"I": "I", "Ii": "II", "Iii": "III", "Iv": "IV"}


def _display(value: str) -> str:
    """Title-case a stored category level for display, preserving roman
    numerals and not capitalising the letter after an apostrophe."""
    words = [_LABEL_FIXUPS.get(w.title(), w.title()) for w in value.split()]
    return " ".join(words).replace("'S", "'s")


def _quality(predictor: BundlePredictor, task: str) -> ModelQuality:
    m, split = predictor.metrics, predictor.split
    trained_on = (f"{split.get('split_on', '?')}-year split, train "
                  f"{split.get('train_years', ['?'])[0]}-{split.get('train_years', ['?'])[-1]}, "
                  f"test {split.get('test_years')}")
    if task == "regression":
        return ModelQuality(
            trained_on=trained_on,
            test_metric=f"RMSE {m.get('test_rmse', float('nan')):.1f} days, "
                        f"MAE {m.get('test_mae', float('nan')):.1f} days",
            baseline_metric=f"RMSE {m.get('baseline_rmse', float('nan')):.1f} days "
                            "(always predict the training median)",
            caveat=(
                "The model beats that baseline by roughly 15%, but its R2 is negative: "
                "it tracks the average better than a constant does, while explaining "
                "little case-to-case variation. Treat the estimate as a rough central "
                "tendency, not a commitment. " + SYNTHETIC_WARNING
            ),
        )
    return ModelQuality(
        trained_on=trained_on,
        test_metric=f"accuracy {m.get('test_accuracy', float('nan')):.3f}, "
                    f"macro-F1 {m.get('test_f1_macro', float('nan')):.3f}, "
                    f"ROC AUC {m.get('test_roc_auc_ovr', float('nan')):.3f}",
        baseline_metric=f"accuracy {m.get('baseline_accuracy', float('nan')):.3f} "
                        "(always predict the majority class)",
        caveat=(
            "This model does NOT beat its baseline. It predicts 'certified' for "
            "essentially every input, and its ROC AUC is close to chance. The "
            "probabilities below are the model's scores and do vary between cases, but "
            "the predicted class is very nearly a constant. Do not read a 'certified' "
            "prediction as evidence the case will be approved. " + SYNTHETIC_WARNING
        ),
    )


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@app.get("/health", response_model=HealthResponse, tags=["meta"])
def health() -> HealthResponse:
    return HealthResponse(
        status="ok" if registry.loaded else "degraded",
        models_loaded=registry.loaded,
        stored_predictions=len(store),
        store_capacity=store.capacity,
        warning=SYNTHETIC_WARNING,
    )


@app.get("/meta/options", response_model=OptionsResponse, tags=["meta"])
def options() -> OptionsResponse:
    """Form options drawn from the model's own category levels.

    A UI that offers a value the model has never seen produces a silently
    degraded prediction, so the choices come from the fitted bundle rather than
    from a hand-maintained list that can drift out of sync with it.
    """
    predictor = registry.regressor or registry.classifier
    if predictor is None:
        raise ModelNotLoadedError("no model is loaded, so options cannot be derived")
    cats = predictor.categories

    def opts(key: str, labeller=None) -> list[FieldOption]:
        return [
            FieldOption(value=v, label=labeller(v) if labeller else v)
            for v in cats.get(key, [])
        ]

    return OptionsResponse(
        soc_codes=opts("soc_code", lambda c: f"{c} - {SOC_CODE_TITLES.get(c, 'Occupation')}"),
        worksite_states=opts("worksite_state",
                             lambda s: f"{s} - {STATE_TO_REGION.get(s, '')}".rstrip(" -")),
        skill_levels=opts("skill_level", _display),
        education_levels=opts("job_education", _display),
        classes_of_admission=opts("class_of_admission"),
        citizenships=opts("citizenship", _display),
        wage_units=[FieldOption(value=u, label=u)
                    for u in ("Year", "Hour", "Month", "Week", "Bi-Weekly")],
        outcome_classes=(registry.classifier.classes if registry.classifier else []) or [],
    )


@app.post("/predict/processing-time", response_model=ProcessingTimeResponse,
          tags=["predict"])
def predict_processing_time(case: CaseInput) -> ProcessingTimeResponse:
    """Predict days from filing to final determination."""
    predictor = registry.require("regressor")
    derived = derive_features(case)
    frame = predictor.build_row(derived)

    days = float(np.clip(predictor.model.predict(frame)[0], 1, None))
    base, shap_values = predictor.shap_for(frame)
    warnings = input_warnings(predictor.features, frame, shap_values,
                              predictor.unseen_categories(derived))

    mae = float(predictor.metrics.get("test_mae", 0.0))
    prediction_id = store.new_id()
    store.put(StoredPrediction(
        prediction_id=prediction_id, task="regression", created_at=utcnow(),
        prediction=days, explained_class=None, base_value=base, units="days",
        contributions=contribution_records(predictor.features, frame, shap_values),
        reconstruction=float(base + shap_values.sum()),
        request=case.model_dump(mode="json"),
    ))

    return ProcessingTimeResponse(
        prediction_id=prediction_id,
        predicted_days=round(days, 1),
        predicted_months=round(days / 30.44, 1),
        likely_range_days=[round(max(1.0, days - mae), 1), round(days + mae, 1)],
        filing_date=case.filing_date,
        estimated_decision_date=estimated_decision_date(case.filing_date, days),
        model_quality=_quality(predictor, "regression"),
        input_warnings=warnings,
        explain_url=f"/explain/{prediction_id}",
    )


@app.post("/predict/outcome", response_model=OutcomeResponse, tags=["predict"])
def predict_outcome(case: CaseInput) -> OutcomeResponse:
    """Predict the case outcome and the probability of each class."""
    predictor = registry.require("classifier")
    derived = derive_features(case)
    frame = predictor.build_row(derived)

    proba = predictor.model.predict_proba(frame)[0]
    classes = predictor.classes or [str(i) for i in range(len(proba))]
    top = int(np.argmax(proba))

    # Explain the predicted class: the contributions that produced this answer.
    base, shap_values = predictor.shap_for(frame, class_index=top)
    warnings = input_warnings(predictor.features, frame, shap_values,
                              predictor.unseen_categories(derived))

    prediction_id = store.new_id()
    store.put(StoredPrediction(
        prediction_id=prediction_id, task="classification", created_at=utcnow(),
        prediction=float(proba[top]), explained_class=classes[top],
        base_value=base, units=f"log-odds of {classes[top]}",
        contributions=contribution_records(predictor.features, frame, shap_values),
        reconstruction=float(base + shap_values.sum()),
        request=case.model_dump(mode="json"),
    ))

    return OutcomeResponse(
        prediction_id=prediction_id,
        predicted_outcome=classes[top],
        confidence=round(float(proba[top]), 4),
        probabilities=[
            OutcomeProbability(outcome=c, probability=round(float(p), 4))
            for c, p in sorted(zip(classes, proba), key=lambda t: -t[1])
        ],
        model_quality=_quality(predictor, "classification"),
        input_warnings=warnings,
        explain_url=f"/explain/{prediction_id}",
    )


@app.get("/explain/{prediction_id}", response_model=ExplanationResponse,
         tags=["explain"])
def explain(prediction_id: str) -> ExplanationResponse:
    """SHAP attribution for a previously returned prediction."""
    record = store.get(prediction_id)
    if record is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"prediction_id {prediction_id!r} is not in the store. The store holds "
                f"the {store.capacity} most recent predictions and is cleared when the "
                "API restarts. Make a new prediction to get a fresh id."
            ),
        )

    if record.task == "regression":
        note = ("Each SHAP value is a number of days added to or subtracted from the "
                "base value. They sum exactly to the prediction.")
    else:
        note = (f"Each SHAP value is a log-odds contribution to the "
                f"'{record.explained_class}' margin, not a probability. They sum to the "
                "class margin; the probability comes from a softmax over all classes.")

    return ExplanationResponse(
        prediction_id=record.prediction_id,
        task=record.task,
        created_at=record.created_at,
        prediction=round(record.prediction, 4),
        explained_class=record.explained_class,
        base_value=round(record.base_value, 4),
        units=record.units,
        contributions=[ShapContribution(**c) for c in record.contributions],
        reconstruction_check=round(record.reconstruction, 4),
        note=note,
    )
